#!/usr/bin/env bash
# a script that localhost resolves to 127.0.0.2, facebook.com resolves to 8.8.8.8.
cp /etc/hosts /etc/hosts.backup
sudo bash -c 'echo "127.0.0.2 localhost" > /etc/hosts'
sudo bash -c 'echo "8.8.8.8 facebook.com" >> /etc/hosts'
