#!/usr/bin/env bash
# Get the hostname of the machine
hostname=$(hostname)
ip_addresses=$(getent hosts "$hostname" | awk '{print $1}')
for ip in $ip_addresses; do
  if [[ $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "$ip"
  fi
done
